### ISSUE TITLE
§2.7.5: missing reference to Mukherjee et al. 2013

### ISSUE THREAD

**Issue by kcopas** [gbif/doc-georeferencing-best-practices#10]
No citation included for the above in the references:
https://docs.gbif-uat.org/georeferencing-best-practices/1.0/en/#digital-elevation-models

**Comment by ArthurChapman** [comment]
Mukherjee S, Joshi PK, Mukherjee S, Ghosh A, Garg RD, Mukhopadhyay A (2013). Evaluation of vertical accuracy of open source Digital Elevation Model (DEM). _International Journal of Applied Earth Observation and Geoinformation_ 21: 205-217. https://doi.org/10.1016/j.jag.2012.09.004
