### ISSUE TITLE
Editing of links and References - §2 Elements for Describing a Location

### ISSUE THREAD

**Issue by ArthurChapman** [gbif/doc-georeferencing-best-practices#13]
- [x] __§2__  Second paragraph "(see §2.5)"  elsewhere in the document you give "(see Coordinate Reference System)".  I don't mind either way, but we need to be consistent throughout the document.  [See for example Polygons under __§2.3.1__ first paragraph.

- [x]  __§2.2__ Example 1. Link for "MVZ Guide for Recording Localities in Field Notes" - should spur a new tab.

- [x] __§2.3.2__ First paragarph - reference to "OBIS n.dat." shouild spur a new tab.

- [x] __§2.3.3__ First paragraph the link to "dwc:footprintWKT" should spur a new tab.

- [x] __§2.3.4__ First paragraph, 7th line second ",coordinate" should be deleted (e.g. "coordinates,coordinate for ..." should be "coordinates for ..." 

- [x] __§2.3.4__ Last paragraph - reference to "§2.3.2." "Paths" with same link.  (See under point 1 above).

- [x] __§2.4.2__ Last paragraph - link for "verbatimCoordinates" should spur a new tab.

- [x] __§2.6__ First paragraph.  (Two) Links to "Novatel 2015". Novatel seem to have changed the link (now just get 404 message).  Change link to "https://novatel.com/support/knowledge-and-learning/gnss-book"  

- [x] __§2.6__ Second paragraph Reference to "(Chapman et al. 2005a)" should be "(Chapman 2005a)".  Link works OK.

- [x] __§2.6__ First Tip point.  We really don't need "in Uncertainty Related to Coordinate Precision" The link to "Table 3" is enough on its own.

- [x] __§2.6.1__ First paragraph. Change link to Novatel 2015 change to "https://novatel.com/support/knowledge-and-learning/gnss-book"  [See point 8 above]

- [x] __§2.6.1__ Second paragraph. Change link to Novatel 2015 change to "https://novatel.com/support/knowledge-and-learning/gnss-book"  [See point 8 above]

- [x] __§2.6.2__  Second paragraph "US Dept of Defence and GPS Navstar 2008" should link to "https://www.gps.gov/technical/ps/2008-SPS-performance-standard.pdf"

- [x] __§2.6.2__  Second paragraph "GPS.gov 2017" should link to "https://www.gps.gov/systems/gps/performance/accuracy/" 

- [x] __§2.6.2__  Second paragraph "Novatel 2015" should link to "https://novatel.com/support/knowledge-and-learning/gnss-book"

- [x] __§2.6.2__  Second paragraph "McElroy et al. 2007" should link to "https://www.spatial.nsw.gov.au/__data/assets/pdf_file/0019/70345/Exploring_GPS.pdf"

- [x] __§2.6.3__ First paragraph. Change link to Novatel 2015 change to "https://novatel.com/support/knowledge-and-learning/gnss-book"  [See point 8 above]

- [x] __§2.6.4__ First paragraph. Change link to Novatel 2015 change to "https://novatel.com/support/knowledge-and-learning/gnss-book"  [See point 8 above]

- [x] __§2.6.8__ First paragraph. Change link to Novatel 2015 change to "https://novatel.com/support/knowledge-and-learning/gnss-book"  [See point 8 above]

- [x] __§2.6.9__ Line 9 "Arturo Ariño yyyy, personal communication, dd mmm" should read Arturo Ariño 2019, personal communication, 24 Oct"

Will continue from __§2.7__ later

**Comment by ArthurChapman** [comment]
- [ ] __§2.7__  at end of Tip.   "Murphy et al. 2004" should link to:  "https://doi.org/10.5281/zenodo.59792"

- [x] __§2.7.3__ First paragraph, second line "GPS/NSS" should read "GPS/GNSS" 

- [x] __§2.7.4__ "(Ellingson 2017)" link no longer works replace with "https://cdn.ymaws.com/www.ispls.org/resource/resmgr/2017_Convention_Handouts/Ellingson_-_Replacing_NAD_83.pdf"

- [x] __§2.8__  Third paragraph, 2nd line the link for "online calculator" should sporne a new tab.

- [x] __§2.9.1__  ""Distance only" locality" does not need to be bolded.

- [x] __§2.9.1__  Line 6 "we don’t know what was being used at the reference" should read "we don’t know what was being used as the reference"

- [x] __§2.9.1__  Line 7  remove ">>"

- [x] __§2.9.3__ Third paragraph "Offset – Distance along a Path" link should sporne a new tab (the previous one "Offset – Distance at a Heading" does).

- [ ] __§2.9.3__  Good to have a hard space in "Figure 12" so they don't split across lines.

- [x] __§2.10.2__  This section probably should have a marine icon near the start.

- [x] __§2.10.2__ First Paragraph There appears to be space before the period at the end of the paragraph that should be deleted.

- [x] __§2.12.1__ First paragraph - seems to be a problem with the formatting for "Gibson 2002"  Also the "Goldsheider & Drew 2014" - see  ([goldsheider]Goldsheider & Drew 2014]

- [x] __§2.12.1__ Second paragraph, Line 7 - add closed bracket after Polygons - e.g. (see Polygons).

- [x] __§2.12.1__ Second paragraph the internal link for "Feature-Cave" doesn't work. It just goes to the top of the publication.

- [x] __§2.12.2__ First paragraph - seems to be a problem with the formatting for "Gibson 2002"  [Same as Point 32 above]

**Comment by kcopas** [comment]
links not possible in tip quote
