### ISSUE TITLE
Editing Links and References - §3 The Georeferencing Process

### ISSUE THREAD

**Issue by ArthurChapman** [gbif/doc-georeferencing-best-practices#14]
- [x] __§3.1.1__ __Georeferencing Phase__  Second dot point. The link to the Geoferencing Calculator should be to "http://georeferencing.org/georefcalculator/gc.html" NOT to the Manual.

- [x] __§3.1.2__ First Paragraph - Link to ORNIS gives a 404 Error - @tucotuco  - do you have the correct link?

[From @tucotuco - replace link with https://sites.google.com/site/ornisnet/georeferencing/workflownew]

- [x] __§3.1.3__ Second Paragraph  link to "GBIF.org" should sporne a new tab.

- [x] __§3.1.3__ Third paragraph - all the links  "decimalLatitude", "decimalLongitude", "geodeticDatum" and "coordinateUncertaintyInMeters" should sporne new tabs.

- [x] __§3.1.3__  Fifth Paragraph, second line add space in "georeferenceand"

- [ ] __§3.1.5__ Fifth Paragraph, fifth line "extent" should have a link to Glossary.

- [ ] __§3.1.5__ Second Tip "See §1.6." should probably be "See Accuracy, Error, Bias, Precision, False Precision, and Uncertainty" for consistency with other parts of the document.

- [x]  __§3.1.5__ First paragraph after Tips.  Reference to "HISCOM 2000," needs to be changes to "Conn 1999" with the new link:  "http://plantnet.rbgsyd.nsw.gov.au/HISCOM/HISPID/HISPID4/Introduction/hispid4.html"

- [x]  __§3.1.5__ Third Paragraph after Tips. Link for "Location" should sporne a new tab and the link altered to                "https://dwc.tdwg.org/terms/#location" 

- [x] __§3.1.5__ Last dot point in section " GeologicalContext" should sporne a new tab and the link altered to "https://dwc.tdwg.org/terms/#geologicalcontext"

- [x] __§3.1.5__  Last paragraph Change link for "Escobar et al. 2015" to "http://repository.humboldt.org.co/handle/20.500.11761/9610"

TO BE CONTINUED FROM §3.2

**Comment by ArthurChapman** [comment]
- [x] __§3.2.2__ First line after the greyed example "bridge over the ..." Link to " Feature – with Obvious Spatial Extent " should sporne a new tab.

- [x] __§3.2.2__ Second paragraph after the greyed example "bridge over the ..." - second line change "georeference,georeferenced" to "georeferenced".  

- [x] __§3.2.2__ Second paragraph after the greyed example "bridge over the ..." - third line change "georeference,georeferenced" to "georeference".  

- [x] __§3.2.2__ Last line before next section the link for Difficult Localities should be to  https://docs.gbif-uat.org/georeferencing-quick-reference-guide/1.0/en/#difficult-localities  [and sporne a new tab]

- [x] __§3.2.3__ under __§Point-radius method__ remove "<" before "boundaries"

- [x] __§3.2.4__ end of First Paragraph link to "dwc:georeferenceVerificationStatus" should sporne a new tab.

- [x] __§3.2.4__ under __§Taxon constraints__ Fourth paragraph, Link to " LifeWatch taxon matching services" should sporne a new tab.

- [x] __§3.3.3__ Second paragraph "Vincenty 1976" should link to the References.

- [x] __§3.3.4__ First Paragraph, eigth line "dwc:footprintWKT" should sporne a new tab.

- [x] __§3.3.4__ First Paragraph, ninth line " dwc:footprintSRS" should sporne a new tab.

- [x] __§3.4.2__  __§Uncertainty in Paper Map Measurements__ 7th paragraph  Link to " United States National Map Accuracy Standards (USGS 1999)" should sporne a new tab.

TO BE CONTINUED FROM Table 1 in __§3.4.2__

**Comment by ArthurChapman** [comment]
NB One reference __(FGDC 1998)__ keeps returning "__The requested service is temporarily unavailable. Please try later__."  I will keep trying and hope it is only temporary.

- [x] __§3.4.2__ __§Using OpenStreetMap, Google Maps and Google Earth__ Second paragraph, first line - change "geographical" to "geographically"

- [x] __§3.4.2__ __§Using OpenStreetMap, Google Maps and Google Earth__ Second paragraph, last line.  I have found a link to (Helbich et al. 2012) on research gate - so add link "https://www.researchgate.net/publication/267857078_Comparative_Spatial_Analysis_of_Positional_Accuracy_of_OpenStreetMap_and_Proprietary_Geodata" 

- [x] __§3.4.2__ __§Uncertainties in Marine Maps__ First paragraph, second line link for "Coastal Navigation" should sporne a new tab.

- [x] __§3.4.2__ __§Uncertainties in Marine Maps__ First paragraph, second line "Coast Navigation" should be "Coastal Navigation 2020"

- [x] __§3.4.3__ Second Paragraph the link to "Georeferencing Calculator (Wieczorek & Wieczorek 2020)" should be to "http://georeferencing.org/georefcalculator/gc.html" and NOT the Manual.

- [x] __§3.4.3__ First tip "False Precision" should link to Glossary

- [x] __§3.4.3__ Second tip "precision" and "coordinate uncertainty" should both link to Glossary.

- [x] __§3.4.4__ Second Paragraph the link to "Georeferencing Calculator (Wieczorek & Wieczorek 2020)" should be to "http://georeferencing.org/georefcalculator/gc.html" and NOT the Manual.

- [x] __§3.4.5__ Last Paragraph the link to "Georeferencing Calculator (Wieczorek & Wieczorek 2020)" should be to "http://georeferencing.org/georefcalculator/gc.html" and NOT the Manual.

- [x] __§3.4.6__ Third paragraph link to "Wieczorek et al. 2004 " should sporne a new tab.

- [x] __§3.4.7__ link to "Wieczorek 2001" should sporne a new tab.

- [x] __§3.4.7__  the link to "Georeferencing Calculator (Wieczorek & Wieczorek 2020)" should be to "http://georeferencing.org/georefcalculator/gc.html" and NOT the Manual.

- [x] __§3.4.7__ the link to "Understanding Uncertainty Contributions" should link to the §9 in the document - currently just goes to top of document.

- [x] __§3.4.8__  the link to "Georeferencing Calculator (Wieczorek & Wieczorek 2020)" should be to "http://georeferencing.org/georefcalculator/gc.html" and NOT the Manual.

- [x] __§3.4.9__ Firt Paragraph.  the link to "Georeferencing Calculator (Wieczorek & Wieczorek 2020)" should be to "http://georeferencing.org/georefcalculator/gc.html" and NOT the Manual.     __ALSO__ for consistency "(Wieczorek & Wieczorek 2020)" should also be included in the link.  __NB__ it should also sporne a new tab.

- [x]  __§3.4.9__ First Paragraph.  the link to "Georeferencing Calculator Manual (Bloom et al. 2020)" should go to "https://docs.gbif-uat.org/georeferencing-calculator-manual/1.0/en/"  currently it goes to GBIF.

- [x] __§3.4.9__ Second Paragraph.  the link to "Georeferencing Calculator Manual (Bloom et al. 2020)" should go to "https://docs.gbif-uat.org/georeferencing-calculator-manual/1.0/en/"  currently it goes to GBIF.

- [x] __§3.4.9__ Third Paragraph. "online" should sporne a new tab.

- [x] __§3.4.9__ Third Paragraph. First link to "GitHub" gets a 404 error  @tucotuco what should this be???

[From @tucotuco remove ":" at end of link - should be  "https://github.com/VertNet/georefcalculator/releases"]   

- [x] __§3.4.9__ Third Paragraph. Second link to "GitHub" should sporne a new tab.

- [x] Cation to __Figure 13__ the link to "(Wieczorek & Wieczorek 2020)" should be to "http://georeferencing.org/georefcalculator/gc.html" and NOT the Manual.

- [x] __§3.5__ First paragraph link to "documented by the MaNIS project" should sporne a new tab.

**Comment by kcopas** [comment]
> - [ ] __§3.1.5__ Fifth Paragraph, fifth line "extent" should have a link to Glossary.

The glossary term 'extent' is already linked once in the same sentence, about a dozen words previously. We're trying to clean up the glossary references to once per section, with the occasional exception for context or clarity. Proximity here suggests that once would be sufficient.

> - [ ] __§3.1.5__ Second Tip "See §1.6." should probably be "See Accuracy, Error, Bias, Precision, False Precision, and Uncertainty" for consistency with other parts of the document.

Will address uniformly through the document per @MattBlissett's recommendation [here](https://github.com/gbif/doc-publishing-sequence-derived-data/issues/40). Closing current issue in favor of that.
