### ISSUE TITLE
Editing Links and References - §6 Maintaining Data Quality

### ISSUE THREAD

**Issue by ArthurChapman** [gbif/doc-georeferencing-best-practices#17]
- [x] __§6__ First Paragraph Link to "Chapman 2005b" doesnot resolve. I think it is the wrong link anyway. Replace with "https://www.gbif.org/document/80528"

- [ ] __§6.2__ Reference to "Chapman 2005a" is wrong - replace with "https://www.gbif.org/document/80528"

- [ ] __§6.2__ Link to " dwc:georeferenceVerificationStatus" should sporne a new tab.

- [x] __§6.3.2__ First Paragraph. Link to "http://georeferencing.org" should sporne a new tab.

- [x] __§6.3.2__ First paragraph after dot points. Link to "http://georeferencing.org" should sporne a new tab.

- [x] __§6.3.2__ Last paragraph. Link to "amendment tests" should sporne a new tab.

- [ ] __§6.3.3__ Links to " dwc:georeferenceVerificationStatus", "dwc:georeferencedBy" and "dwc:georeferencedDate" should sporne new tabs.

- [x] __§6.4__ Link to "Principles of Data Quality^ (Chapman 2005a)" should sporne a new tab.

- [x] __§6.4__ Revove "^" from  "Principles of Data Quality^"

- [x] __§6.4__  First dot point "[georeferencing]" should be a link to the glossary and have brackets removed.

- [x] __§6.4__  Third dot point. Delete ">"

- [x] __§6.4__  Fourth dot point. Link to "Zermoglio et al. 2020" should sporne a new tab.

- [x] __§6.4__  Fifth dot point. Link to "Wieczorek & Wieczorek 2020" should sporne a new tab.  __ALSO__ Link should be to "http://georeferencing.org/georefcalculator/gc.html" NOT to the Manual.

**Comment by kcopas** [comment]
Closing—unresolved points covered under #20

**Comment by kcopas** [comment]
Closing—unresolved points covered under #20
