### ISSUE TITLE
1km on Figure 12 is wrong

### ISSUE THREAD

**Issue by qgroom** [gbif/doc-georeferencing-best-practices#24]
The 1km bar in figure 12 should probably be 2km. Either that, or this webpage with the same example is wrong...
http://georeferencing.org/georefcalculator/docs/GeorefGuide.html#imprecision_in_coordinates

**Comment by RicardoOrtizG** [comment]
I think this is part of the adaptation of Wieczorek (2004), for this new method takes only half of the uncertainty if I am understanding right. This is why in this case the uncertainty is 0.5 km and not 1 km like the older version of the method.

**Comment by tucotuco** [comment]
@RicardoOrtizG is correct. Table 12 is correct and the explanation for it is in the paragraph just above it.
