### ISSUE TITLE
Systematically mis-represented +/-

### ISSUE THREAD

**Issue by tucotuco** [gbif/doc-georeferencing-best-practices#25]
In section 2.7.7 I found two instances where the - part of ± is missing, showing only the plus. From the original it looks like these two instances were underlined + signs rather than the ± symbol. The actual symbol instances look fine throughout the document.

**Comment by ArthurChapman** [comment]
Good pickup @tucotuco

**Comment by kcopas** [comment]
Just to be clear: you’re most welcome to edit these, too, @tucotuco — especially when they such painstaking details!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by tucotuco** [comment]
We will coordinate making as many changes as we can after the review period is over. I have created the label Ready to implement for issues on which there is consensus to make the change. I have added that label for this issue.
