### ISSUE TITLE
Suggestion for chapter 3.4.5 to better understanding on the formula

### ISSUE THREAD

**Issue by RicardoOrtizG** [gbif/doc-georeferencing-best-practices#29]
I have a suggestion about chapter 3.4.5. I think is necessary to specify the values in the formula like the Wieczorek 2004 article. "where x=dcos(θ), y=dsin(θ), x’=dcos(θ’),  and y’=dsin(θ’). Just for a quick understanding of the formula and his application in this example. It could be helpful also for a better understanding of the values **d**, **(θ)**, and the value of x and x' mentioned in the text.

**Comment by ArthurChapman** [comment]
In **§3.4.5**

After the formula 

**replace** line "and the uncertainty in the above example would be 3.90 km"

**with**  "where x=dcos(θ), y=dsin(θ), x’=dcos(θ’), and y’=dsin(θ’). The uncertainty in the above example would be 3.90 km."

**Comment by ArthurChapman** [comment]
File edited. Closing issue
