### ISSUE TITLE
Title text is missing for XKCD image

### ISSUE THREAD

**Issue by DavidFichtmueller** [gbif/doc-georeferencing-best-practices#30]
This is a minor issue, but I noticed that at the end of section 1.6, the image from [XKCD 2170: Coordinate Precision](https://xkcd.com/2170) is missing the title text. On an XKCD image there is always another joke in the title tag of the image, which can be seen when hovering over the image with the mouse. In this case it is: "40 digits: You are optimistic about our understanding of the nature of distance itself." I think this could be included as a title tag in the online version of the guide as well.

**Comment by tucotuco** [comment]
Love it.
