### ISSUE TITLE
Doubt about the threatment of elevation uncertainty

### ISSUE THREAD

**Issue by RicardoOrtizG** [gbif/doc-georeferencing-best-practices#32]
I'm glad to see all of these considerations for the elevation accuracy, but I'm not sure how to document these uncertainties if I want to recover the elevation based on the georeference coordinates or just adjust them based on the best practices recommendations. For example: Having a range of elevation of 3200-3400 meters in a dataset with an unknown elevation source (like most of the time), I could use the consideration of uncertainties for unknown elevations mentioned in 2.7.2. if I'm trying to catch the coordinate between two contours in a elevation digital map. Then If I want to adjust the elevation, ¿Do I have to change the elevation based on the radius of the whole calculated uncertainty or just taking in count half of the contour interval for elevation uncertainty?. of course saving the original elevation in verbatimElevations.

**Comment by tucotuco** [comment]
I hope I understand you correctly. Does the section on "Contour lines" under "2.1.3.3. Feature – Path" in the Quick Reference Guide (https://docs.gbif-uat.org/georeferencing-quick-reference-guide/1.0/en/#offset-along-a-narrow-path) provide the solution to your question?

**Comment by ArthurChapman** [comment]
It is best - in verbatimElevation - to record the range as we don't (currently) have an uncertainty field associated with Elevation.  So, to accurately record the elevation, one should record the elevation range within the Uncertainty radius.  Elevation can, of course, often help refine the coordinates if one can be certain of trhe accuracy of that elevation. This can be particularly important in areas of steep gradients.

**Comment by ArthurChapman** [comment]
Nothing needs to be added to the document for this issue
