### ISSUE TITLE
Document not found

### ISSUE THREAD

**Issue by RicardoOrtizG** [gbif/doc-georeferencing-best-practices#33]
Maybe the document on the site is down but when I look for this document only found the MVZ landing page and not the cited Guide for Recording Localities in Field Notes (saw it in section 2.2. Localities, example 1).

**Comment by ArthurChapman** [comment]
@tuco I thought we had fixed this one.  Also in the References under "Museum of Vertebrate Zoology (2006)"

**Comment by tucotuco** [comment]
The MVZ recently revamped their web site. I asked and that document is no longer offered by the MVZ and is instead incorporated into this document at this subheading:

https://mvzhandbook.berkeley.edu/curatorial/tutorials-training/localities-events

**Comment by kcopas** [comment]
updates committed to review-edits branch
