### ISSUE TITLE
2.2 Recommendation to avoid the use of quotations marks in localities descriptions

### ISSUE THREAD

**Issue by RicardoOrtizG** [gbif/doc-georeferencing-best-practices#34]
Another good practice that I think is needed to be recommended in 2.2. Localities section is avoiding the use of quotation marks ("") in localities, in some cases could generate a lot of problems to open text files or even when loading the files in the IPT.

PD: maybe the use of quotations marks in the best practice guide examples can induce this particular error.

**Comment by tucotuco** [comment]
Assigned to @ArthurChapman since he'll be in there editing anyway.

**Comment by ArthurChapman** [comment]
New TIP incorporated into document and quotes removed from example. Issue closed
