### ISSUE TITLE
3.1.1 Some steps could be added to the Georeferencing Project Workflow

### ISSUE THREAD

**Issue by RicardoOrtizG** [gbif/doc-georeferencing-best-practices#35]
It is important to include in the data preparation phase the maintenance of the original geographic information in the corresponding textual DwC elements, before the start or before the changes are made, it is a point of security if there is an error in the process.

**Comment by tucotuco** [comment]
@tucotuco making a revision of the entire section 3.1.

**Comment by tucotuco** [comment]
Solved with 21d3d590b2a9dadee1484710649a59b4f061fe97
