### ISSUE TITLE
3.1.1 Data preparation phase locality meaning

### ISSUE THREAD

**Issue by RicardoOrtizG** [gbif/doc-georeferencing-best-practices#36]
I think that the meaning of locality in the step "Extract different localities" in the data preparation phase, should be broader, because it is not only the description of the locality that is the source of the georeferencing, but it also includes the elevation, the coordinates textual and superior geographic information. For example, a locality: Río Negro, is different from the same locality documented with elevation. Similar cases with the higher geography, for example, Colombia have more than 3 _Río Negro_ in 3 different states (_Departments_). So, my suggestion is to mention that the different locaties not only correspond to the textual description, but other geographic information such as the ones mentioned above (stateProvince, county, locality, elevation, depth, coordinates, etc.) must be taken into account.

**Comment by ArthurChapman** [comment]
I presume you are talking about §3.1.1  this refers to "extract __distinct__ localities" not "extract different localities". This is in reference to developing unique identifiers (GUIDs) for distinct localities. To identify what are each distinct locality, one would need the extra information as you describe.  What we are suggesting is that (as in your example) you extract the three different _Rio Negro_s and then give each a unique identifier. This can be valuable for georeferencing each at later times.

Perhaps we could change the line to "Identify and extract distinct localities ..."   (@tucotuco ?)

**Comment by tucotuco** [comment]
This whole section needs revision after what Paula had to go to to try to
interpret it for a presentation on the subject in tomorrow's webinar. To
just add "Identify and will not go well with the rest of that sentence. I
think rather that what that sentence needs is a reminder that locality
consists of the combination of everything to do with place, not just a
specific locality string or a single entity.

**Comment by tucotuco** [comment]
Addressed with 5205a226581bfdaf03e0fadea241343abab1a042
