### ISSUE TITLE
3.2.4: Adding elevation constraints

### ISSUE THREAD

**Issue by RicardoOrtizG** [gbif/doc-georeferencing-best-practices#38]
3.2.4. Applying Spatial Constraints chapter is very important even to define the scope of specificity in the georeference process, I think that the elevation constraint was mentioned but not emphasized, and it is a big constraint for countries with varied topography. From experience, I know that try to georeference using elevation for each locality takes a lot of extra time of georeferencing. In some cases, we use it only to reduce uncertainty due to extension but not for all localities because may be overwhelming. ¿Maybe the elevation constraints could be added like the Using Date Constraints?

**Comment by ArthurChapman** [comment]
In __§3.2.4__ before the section “__Using Collector Itineraries__” Add: 

==== Using Elevation Constraints

Elevation can often be used as a constraint to distinguish between two similarly named localities or to refine the uncertainty in a georeference. If both maximum and minimum elevations are given, then the contours may be used to refine a locality and its uncertainty as described in docs.gbif-uat.org/georeferencing-quick-reference-guide/1.0/en/#img-mountain-boundaries[Figure 5^] in https://docs.gbif-uat.org/georeferencing-quick-reference-guide/1.0/en/[Georeferencing Quick Reference Guide (Zermoglio et al. 2020)^].

**Comment by ArthurChapman** [comment]
@kcopas When I tried to add a link out to Figure 5 (Quick Reference Guide) it does not seemed to work properly.  Not sure what I am doing wrong - can you please check

**Comment by tucotuco** [comment]
I'm not sure anything is wrong with it. All the links to the QRG look like
that in the markdown in the repository.

**Comment by kcopas** [comment]
It looks right to me. But since we're making edits on a branch, the changes are not reflected in the document. Will leave it open so we don't overlook checking once we merge the branch.

**Comment by tucotuco** [comment]
Further addressed with 4d3e42f4b3b3105e097cc533f575f8f8638d83c8
