### ISSUE TITLE
Rewrite section 2.2.3.1. Offset along a Narrow Path

### ISSUE THREAD

**Issue by tucotuco** [gbif/doc-georeferencing-best-practices#41]
It occurred to me while resolving one such locality, that the use of the corrected center on the relevant part of the path is not the best reference point, nor is using the radius of the reference entity to add to the final coordinates. It would be fine if all the route was straight, but that is never the case, which means the method described is always going to be bigger than it needs to be. That in itself is conservative, so not "wrong", but it could be better.

**Comment by ArthurChapman** [comment]
Moved to https://github.com/gbif/doc-georeferencing-quick-reference-guide/issues/11 as refers to Quick Reference Guide
