### ISSUE TITLE
Check how you mention Google Maps and Google Earth

### ISSUE THREAD

**Issue by pzermoglio** [gbif/doc-georeferencing-best-practices#44]
Google Maps and Google Earth should be named Google Maps<sup>TM</sup> and Google Earth<sup>TM</sup> throughout the document.

**Comment by tucotuco** [comment]
These were in the original and removed, except for in one quote. Any
particular reason why @MattBlissett or @kcopas ?

**Comment by kcopas** [comment]
We do not use trademarks. Only reason there’d be one here is that I missed it n

=====
Kyle Copas
GBIF Secretariat
+45 28 75 14 75

Sent from my iPhone: thumbs don’t fejl mig nu
________________________________

**Comment by tucotuco** [comment]
OK, we'll remove the one that remains.

**Comment by tucotuco** [comment]
Fixed in bcac51e91ecbc0af1ed7c8add6c83f89f1e6ed94.
