### ISSUE TITLE
Broken link to georeferencing quick reference guide

### ISSUE THREAD

**Issue by RicardoOrtizG** [gbif/doc-georeferencing-best-practices#49]
The link for the georeferencing quick reference guide in the introduction seems to be broken. 
Link:
http://mb.gbif.org/georeferencing-quick-reference-guide/1.0/en/

**Comment by ArthurChapman** [comment]
Not sure what that problem is - up to GBIF but use the DOI
https://doi.org/10.35035/e09p-h128 - that works.

**Comment by kcopas** [comment]
Check the domain @RicardoOrtizG —not sure how or where you got it, but it’s a personal/test environment set up by @MattBlissett. 

Correct domain and DOI are functioning. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by MattBlissett** [comment]
Hmm, my test server is outranking the real document on a Google search, possibly because the content was visible there for a long time.

I've set up redirects from the test server to the real server.
