### ISSUE TITLE
"Glossary link salad"

### ISSUE THREAD

**Issue by MattBlissett** [gbif/doc-georeferencing-best-practices#5]
I read through the document (and fixed some AsciiDoctor syntax as I went -- work in progress!) while working on our geocoding service, which is the first time I've read it as a user rather than developing the documentation system.

I think there's a "link salad" with [some sections](https://docs.gbif-uat.org/georeferencing-best-practices/1.0/en/#Elevation-GPS) having repeated links not only within the section, not only within the paragraph, but within the same sentence!  I find this distracting.

* Is it useful to link to GPS 9 times in two paragraphs?  Would one -- or even zero -- times be sufficient?
* Must we think of an alternative style for glossary links?  At least with the easy syntax `<<GPS>>` this isn't possible, so it would make the document source code less readable. 

I'm reminded of Wikipedia's Manual of Style on inter-document links: https://en.wikipedia.org/wiki/Wikipedia:Manual_of_Style/Linking#What_generally_should_not_be_linked

(_I realize the GPS link and others go to the wrong place, sections rather than glossary definitions. I don't want to fix this, only for us to decide to remove the links._)

**Comment by ArthurChapman** [comment]
@MattBlissett I don't think you are working on the final document. We sent @kcopas  an early version (back in November 2019) we were still working on so that he could work out how to get it into ASCII Docs.  This was not meant to be the final doc. After that we continued extensive editing and sent a link to the final version https://docs.google.com/document/d/1K0iku7Z4FC2lKzXVLLJKsnDEwXRJNbcJwWhspX4hiXg/edit#heading=h.30j0zll.  in March this year.

WRT to links to the glossary - we originally just had a small icon before each Glossary reference without a link, but it was decided with @kcopas earlier that links would be better.  We have experimented with several ways - including only linking the first reference within a section but in the end decided to go with wghat we currently have.  BTW - the latest version of the document had all the glossary links done for you - I hope you have not been doing extra work.

**Comment by MattBlissett** [comment]
I thought I was using https://docs.google.com/document/d/1nTz6TMK7j3pdwcbneUrSzFMPlmgLnSCCaw7XgzhFM5E/edit, which is the one from the March email.

Exporting both Google Documents to plain text shows just 3 characters difference; `(see <<Figure 9>>BB)` → `(see <<Figure 9>>B)` and `(see <<Figure 9,Figure 9B>>, <<Figure 10,10>>)` → `(see <<Figure 9, Figure 9B>>, <<Figure 10>>)`.

If I've mixed things up, I can redo the import.  I have a few regex search-replace operations to do 90% of the work (the export often has things like `<<**GPS>>**` rather than `<<GPS>>` or `*<<GPS>>*`, then the remaining parts are things that don't convert correctly: sub-bulleted lists, images, equations, etc.

**Comment by tucotuco** [comment]
That is indeed the right document, but the content on
https://docs.gbif-uat.org/georeferencing-best-practices/1.0/en/ doesn't
correspond to that. The Table of contents is the best place to compare.
Aside from completely different numbering, check section 1.4 Three
Dimensional Shapes in the ASCII Doc version, it doesn't exist in the final
draft.

We were talking about the links to Glossary terms. They don't bother us,
but we have been staring at them for a long time. Something that would be
ideal, if it is possible, would be to bring up the Glossary entry in an
information box when hovering over a linked term. Do you know it that can
be done? It would allow people at any place in the text to review the
definition without going to the Glossary and losing their place. If it
isn't easy, maybe it is worth thinking about having the Glossary separate,
so it can be open in another window and thereby have a similar effect on
experience. Just ideas.

**Comment by MattBlissett** [comment]
I re-imported the document, so it should be the latest version.

Bringing up the definition when hovering over a glossary term isn't functionality that already exists in the document system, so it would need to be added.  But, the current links shouldn't cause people to lose their place, as the "back" button should return to the previous position.

**Comment by tucotuco** [comment]
Ok, great. The back button sounds like a satisfactory solution.

**Comment by ArthurChapman** [comment]
Looks much better on a brief glance @MattBlissett. I will look in more detail early next week.  I like the way the back-button works.  Doesn't work in the pdf version though - and the Title Page of the PDF version will need fixing.  I will look at it in detail next week.

**Comment by kcopas** [comment]
I can't stress this enough: the PDF is a secondary format provided for printable convenience and (to a lesser extent) archiving of major versions. No back button needed.

Apologies for the long delay. I expect that the arrival of the signature on the BID contract will keep me away from this work for a few days more, but I will be advancing it in coming days.

**Comment by MattBlissett** [comment]
The PDF links do work on the built-in PDF viewer of Firefox, including going back-and-forwards.  They also work in the default KDE (Linux) viewer, but the back/forward buttons don't work in Chrome's built-in viewer.  This seems like a limitation of the PDF viewer, rather than a problem with the document -- I don't think there's a reasonable alternative anyway.

In the future, the PDF might only be useful for printing, with an EPUB format book  produced for electronic (e-reader etc) use.  However, the AsciiDoctor→EPUB converter is still under development, and support for crossreferences between chapters is possible, but annoying to use.

(NB the [other](https://docs.gbif-uat.org/georeferencing-quick-reference-guide/1.0/) [two](https://docs.gbif-uat.org/georeferencing-calculator-manual/1.0/) documents are partly converted, but it's probably best to get this document in a near-finished state before raising issues with those.)

**Comment by ArthurChapman** [comment]
It looks good. I have only checked layout. Some things I noticed
1. [x] The References are not yet linked (see 10. below)
2. [x] Not sure the Glossary links need be bolded - it makes it look a bit clunky - but I can accept it.  I would nearly make them reversed - the links to the Glossary not bold, but the link to sections Bolded.
3. [x] "location" in dotpoints under 1.4 should be bold.
4. [x] I would indent Figure captions - but not important.
5. [x] 1 dot points undet 3.1 "location" boldrd nut not linked.
6. [x] Under 3.1.1 second paragraph "Quality" bolded but not linked.
7. [x] Under 3.2.3 there are a lot of Glossary terms bolded but not linked.
8. [x] Under 3.3.5 "Shape" is bolded but not linked.
9. [x] Under 3.4.1 "extent" and "radial" bolded but not linked
10. [x] The references are missing and need to be included.

_Edited by Matt to add checkboxes to each point._

**Comment by MattBlissett** [comment]
For some reason, "Save as OpenDocument" on Google Docs puts the references in a very long page header, so they were missed.  I've added the section, and made the small changes.

I'm not sure what the best way to link is.  AsciiDoctor has a suggestion: https://asciidoctor.org/docs/user-manual/#user-biblio, but it's not mandatory.  Whatever way is chosen, since there aren't links in the source document they will need to be added more-or-less one-by-one.

**Comment by ArthurChapman** [comment]
Let me know what needs to be don.  Similar to the Glossary, I guess. Let me know and I can probbaly to it in ASCIDocs if I get some time.

**Comment by MattBlissett** [comment]
(Moving my comment on the references to #2.)

**Comment by kcopas** [comment]
Probably still some sections with multiple glossary links within them, but I'll likely go blind trying to find them at this point. Good enough—we'll fix them when we find them.

**Comment by kcopas** [comment]
Probably still some sections with multiple glossary links within them, but I'll likely go blind trying to find them at this point. Good enough—we'll fix them when we find them.
