### ISSUE TITLE
5.1. Mapping to Darwin Core | Doubt about use of locationAccordingTo

### ISSUE THREAD

**Issue by RicardoOrtizG** [gbif/doc-georeferencing-best-practices#50]
In this section the element is defined like dwc:locationAccordingTo: the source authority for the location information, not the georeference information, for which see dwc:georeferenceSources.

I want to map if the original coordinates were taken under GPS or Google Maps, I consider the locationAccordingTo the right element to do that. Let me know if it's correct to use this element for the purpose I want, or maybe is better to use the locationRemarks element

**Comment by tucotuco** [comment]
We would recommend georeferenceSources for "GPS" and "Google Maps" - the
coordinates come from those sources.
