### ISSUE TITLE
Clarification on Extended QDG

### ISSUE THREAD

**Issue by peterdesmet** [gbif/doc-georeferencing-best-practices#54]
In the section on Quarter Degree Grid Cells it is mentioned:

https://github.com/gbif/doc-georeferencing-best-practices/blob/e5e2b76aa4f7b15ced729cd35262a00393629b1d/0200-elements-for-describing-a-location.en.adoc?plain=1#L115

The cited [Larsen et al. 2009](https://doi.org/10.1111/j.1365-2028.2008.00997.x) _does_ extend it to the Northern Hemisphere. I would add that reference there.

The text also mentions:

https://github.com/gbif/doc-georeferencing-best-practices/blob/e5e2b76aa4f7b15ced729cd35262a00393629b1d/0200-elements-for-describing-a-location.en.adoc?plain=1#L110

This is true for QDG, but threw me off for the Extended QDG, which has its origin in the top-left in the Southern, but bottom-left in the Northern hemisphere.

**Comment by ArthurChapman** [comment]
Thanks @peterdesmet I will look into this. Appreciate the information.

**Comment by ArthurChapman** [comment]
@peterdesmet I have rewritten that section.  A draft can be seen at https://docs.google.com/document/d/1Wsp_RWP2Ujnug6J1RpkeMi1qqj21Ia35.  Please check it out before I have that section replaced.

**Comment by peterdesmet** [comment]
Looks good! Note that the abbreviation is `QDGC` not `QDCC`

**Comment by ArthurChapman** [comment]
Good pick up - thanks

**Comment by laurarussell** [comment]
@peterdesmet we've updated the grids section on UAT based on Arthur's Google doc. In the spirit of community review, would you take a look before we release it live? Thanks! https://docs.gbif-uat.org/georeferencing-best-practices/1.0/en/#grids

**Comment by peterdesmet** [comment]
I have reviewed the changes in the [QDGC section](https://docs.gbif-uat.org/georeferencing-best-practices/1.0/en/#quarter-degree-grid-cells). The text is very understandable and addresses the changes between QDGC and the older QDS clearly. Thanks for the update!
