### ISSUE TITLE
Missing or incorrect citation in §2.6.4

### ISSUE THREAD

**Issue by kcopas** [gbif/doc-georeferencing-best-practices#7]
There's a [citation](https://docs.gbif-uat.org/georeferencing-best-practices/1.0/en/#satellite-based-augmentation-system
) to a 2004 FAA doc that's not in the references:

> Satellite Based Augmentation System (SBAS) is a collection of geosynchronous satellites originally developed for precision guidance of aircraft (Federal Aviation Administration 2004)

I think the reference is either missing or misdated (FAA docs from 2017 and 2019 *are* in references).

**Comment by ArthurChapman** [comment]
Sorry about that @kcopas . There is an updated reference just published that is better that the earlier FAA one.  In text: replace "(Federal Aviation Administration 2004) " with "(FAA 2020)"

Reference:

FAA (2020). SBAS Worldwide. DC: Federal Aviation Administration. https://www.faa.gov/about/office_org/headquarters_offices/ato/service_units/techops/navservices/gnss/library/factsheets/media/SBAS_Worldwide_QFact.pdf

That is the trouble with this topic - everything is moving so fast, so the sooner we can get it published the better.

@tucotuco That is a good reference and summarises SBAS up well.

**Comment by kcopas** [comment]
Not a problem, @ArthurChapman—been chipping away steadily at the three georeferencing docs this week. They're all in need of lots of line-by-line attention and formatting. 

Don't forget that the 'trouble' you mention highlights how much more forgiving and accommodating this format is for picking up changes and updates. 

I'll pick up this one shortly…
