### ISSUE TITLE
§2.7.4: Is AGOQ 2017 a reference?

### ISSUE THREAD

**Issue by kcopas** [gbif/doc-georeferencing-best-practices#8]
I've added a link to McCubbin, but is the previous parenthesis a citations or simply an acronym/standard? 
https://docs.gbif-uat.org/georeferencing-best-practices/1.0/en/#vertical-datums

**Comment by tucotuco** [comment]
That is just an acronymized identifier (a synonym) for the datum.

**Comment by kcopas** [comment]
Thanks @tucotuco !

And just to be absolutely clear: the year here is important for distinguishing that version of the AGOQ–correct?

**Comment by tucotuco** [comment]
I'm not sure it is ambiguous without it, but it is customary to include the
year to signify a version.

**Comment by ArthurChapman** [comment]
Agree with @tucotuco and the year is part of the acronym - similar to GDA2020 for Geocentric Datum of Australia 2020, etc.  It is expected to be regularly updated - although it looks like the 2020 version with a modified methodology is being called AUSGeoid2020
