### ISSUE TITLE
§2.10.1: NCEI-NOAA 2019 reference

### ISSUE THREAD

**Issue by kcopas** [gbif/doc-georeferencing-best-practices#9]
https://docs.gbif-uat.org/georeferencing-best-practices/1.0/en/#water-depth-bathymetry

Citation at the end of paragraph 3 here calls out '(NCEI-NOAA 2019).' Is that the same as this?

> NOAA/NCIE & CIRES (2019) US/UK World Magnetic Model. Epoch 2020.0. Main Field Declination (D). https://www.ngdc.noaa.gov/geomag/WMM/data/WMM2020/WMM2020_D_BoZ_MILL.pdf

**Comment by kcopas** [comment]
A second one in the section's final paragraph:

> see the Bathymetric Data Viewer (NOAA 2019))

Is that reference missing, because the current short citation for that doesn't seem right:

> NOAA (2019) World Magnetic Model. https://www.ngdc.noaa.gov/geomag/WMM/

 Seems like were probably headed to NOAA 2019a and b…

**Comment by tucotuco** [comment]
I have to defer to @ArthurChapman for these two.

**Comment by ArthurChapman** [comment]
I am still working on the first one.

The second reference has been updated.   

In text probably should now be (NCEI 2020)

NCEI (2020). Bathymetric Data Viewer. National Centers for Environmental Information. NOAA. Version 2.19.0. https://www.ngdc.noaa.gov/maps/bathymetry/

**Comment by ArthurChapman** [comment]
The first one 

     Citation at the end of paragraph 3 here calls out '(NCEI-NOAA 2019).' Is that the same as this?

- this is complicated in knowing how to cite this. It is not clear from the web sites. If you go back in the http - you get to NOAA's GeoPlatform, but this reference is part of the NCEI - badly set up web sites for citing.

It is not the same as NOAA/NCIE & CIRES (2019)

--

The citation should be (NOAA/NCEI 2019)

Reference

NOAA/NCEI (2019) GEBCO_2019 Bathymetric Contours (NOAA NCEI Visualization). https://noaa.maps.arcgis.com/home/item.html?id=a751dd63f6c744e8bb7d6203266166d8
